### ISSUE TITLE
alternative text and special symbols

### ISSUE THREAD

**Issue by RArchi** [automatix/portfolio#10]
how can I fix these gliches? edit the source table? (&laquo;&raquo; _vs._ `&laquo; &raquo;` _vs._ Alt+174 Alt+175)
![snag_20151018_01](https://cloud.githubusercontent.com/assets/11867931/10563090/cad69c98-758b-11e5-8748-3238941f9cac.jpg)
how we can do this in the future to avoid such problems?
no tags in texts? [alternative characters?](http://www.tedmontgomery.com/tutorial/altchrc.html) CMS?)))

**Comment by RArchi** [comment]
and then it pops up an important topic: how, in principle, to change texts (and other data) between versions.

**Comment by automatix** [comment]
In contrast to the rest text, the ALT-text of an IMG doesn't get parsed. So, we need real `«` and `»` in the database.
